require'barbar'.setup {
	animation = false,
	clickable = true,
	exclude_ft = {'javascript'},
	exclude_name = {'package.json'},
	focus_on_close = 'left',
	highlight_inactive_file_icons = true,
	highlight_visible = true,
	icons = {
		buffer_index = false,
		buffer_number = false,
		button = '×',
		diagnostics = {
		  [vim.diagnostic.severity.ERROR] = {enabled = false},
		  [vim.diagnostic.severity.WARN] = {enabled = false},
		  [vim.diagnostic.severity.INFO] = {enabled = false},
		  [vim.diagnostic.severity.HINT] = {enabled = false},
		},
		gitsigns = {
		  added = {enabled = false},
		  changed = {enabled = false},
		  deleted = {enabled = false},
		},
		filetype = {
		  custom_colors = false,
		  enabled = true,
		},
		separator = {left = '', right = ''},
		separator_at_end = false,
		modified = {button = '●'},
		pinned = {button = '', filename = true},
		preset = 'default',
		alternate = {filetype = {enabled = true}},
		current = {buffer_index = false},
		inactive = {button = '×'},
		visible = {modified = {buffer_number = false}},
	},
	insert_at_end = true,
	maximum_padding = 1,
	minimum_padding = 1,
	maximum_length = 30,
	minimum_length = 0,
	semantic_letters = true,
	sidebar_filetypes = {
		NvimTree = true,
		undotree = {text = 'undotree'},
		['neo-tree'] = {event = 'BufWipeout'},
		Outline = {event = 'BufWinLeave', text = 'symbols-outline'},
	},
	letters = 'asdfjkl;ghnmxcvbziowerutyqpASDFJKLGHNMXCVBZIOWERUTYQP',
	no_name_title = nil,
}

